version: 0.1.0-{build}
image: Visual Studio 2017
configuration: Release

branches:
  only:
    - master

environment:
  COVERALLS_REPO_TOKEN:
    secure: YeKsMYgc+mNFE+yN5S0r5A6cY50tElPf0e8fIDhdDtdbZ8HWDHgOd5eejr/wO+Gy

build_script:
  - ps: .\build\build_all.ps1

test_script:
  - ps: .\build\run_tests.ps1

artifacts:
  - path: 'src\**\*.nupkg'
  - path: 'tools\**\*.nupkg'
