version: 1.0.0.{build}
image: Visual Studio 2015
configuration: Release

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: "{version}-pre"

environment:
  COVERALLS_REPO_TOKEN:
    secure: YeKsMYgc+mNFE+yN5S0r5A6cY50tElPf0e8fIDhdDtdbZ8HWDHgOd5eejr/wO+Gy

before_build:
  - cmd: dotnet restore

build_script:
  - cmd: dotnet build -c Release src\Crest.Core
  - cmd: dotnet build -c Release src\Crest.Host
  - cmd: dotnet build test\Core.UnitTests
  - cmd: dotnet build test\Host.UnitTests

test_script:
  - ps: .\build\run_tests.ps1
